export const htmlClasses = Object.freeze({
  heartIsHot: 'pf-heart-is-hot',
  showBookmarks: 'pf-show-bookmarks',
  numberOfBookmarks: 'pf-number-of-bookmarks',
  heartWrap: 'pf-heart-wrap',
  heart: 'pf-heart',
  bar: 'pf-bar',
  title: 'pf-title',
  btn: 'pf-btn',
  login: 'pf-login',
  share: 'pf-share',
  close: 'pf-close',
  overlay: 'pf-overlay',
  list: 'pf-list',
  row: 'pf-row',
  sort: 'pf-sort',
  link: 'pf-link',
  del: 'pf-del',
  on: 'pf-on',
  off: 'pf-off',
  heartForAnotherPage: 'pf-heart-for-another-page',
  heartForAnotherPageInner: 'pf-heart-for-another-page-inner',
  noBookmarks: 'pf-no-bookmarks',
  hasBookmarks: 'pf-has-bookmarks',
  heartForCurrentPage: 'pf-heart-for-current-page',
})
